from . import views
from django.urls import path, re_path
from rest_framework.authtoken.views import obtain_auth_token
from .views import CreateUserAPIView, LogoutUserAPIView, VideoUploadView


urlpatterns = [
    path('', views.main),
    re_path(r'^auth/login/$',
        obtain_auth_token,
        name='auth_user_login'),
    re_path(r'^auth/register/$',
        CreateUserAPIView.as_view(),
        name='auth_user_create'),
    re_path(r'^auth/logout/$',
        LogoutUserAPIView.as_view(),
        name='auth_user_logout'),
    re_path(r'^auth/check_token/$',
        views.CheckAuthView.as_view(),
        name='check_auth'),
    re_path(r'^media/upload/$',
        views.VideoUploadView.as_view(),
        name='image_upload'),
    re_path(r'^media/upload_hls/$',
        views.HLSUploadView.as_view(),
        name='hls_upload'),
    re_path(r'^media/post/$',
        views.PostVideoView.as_view(),
        name='post_video'),
    re_path(r'^media/get_feed/$',
        views.GetFeedView.as_view(),
        name='get_video'),
    re_path(r'^post/like/$',
        views.LikePostView.as_view(),
        name='like_video'),
    re_path(r'^media/get_user_posts/$',
        views.GetUserPostsView.as_view(),
        name='get_user_posts'),
    re_path(r'^media/delete_post/$',
        views.DeletePostView.as_view(),
        name='delete_post'),
    re_path(r'^post/add_comment/$',
        views.AddCommentView.as_view(),
        name='add_comment'),
    re_path(r'^post/get_comments/$',
        views.GetCommentsView.as_view(),
        name='get_comments'),
    re_path(r'^post/update_posts_engagement/$',
        views.UpdatePostsEngagementView.as_view(),
        name='update_posts_engagement'),
    re_path(r'^user/reset_user_engagement/$',
        views.ResetUserEngagementView.as_view(),
        name='reset_user_engagement'),
    re_path(r'^user/get_preferences/$',
        views.ReturnUserPreferences.as_view(),
        name='get_preferences'),
    re_path(r'^post/report_video/$',
        views.ReportVideoView.as_view(),
        name='report_video'),
    re_path(r'^user/add_follower/$',
        views.AddFollowerView.as_view(),
        name='add_follower'),
    re_path(r'^user/block_user/$',
        views.BlockUserView.as_view(),
        name='block_user'),
    re_path(r'^user/delete_account/$',
        views.DeleteAccountView.as_view(),
        name='delete_account'),
    re_path(r'^user/search/$',
        views.SearchUserView.as_view(),
        name='search_user'),
    re_path(r'^user/get_followers/$',
        views.FollowingListView.as_view(),
        name='get_followers'),
]